<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>

<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="block block-new-customer" style="width: 30%; padding: 25px; border-radius: 25px; background: #fff; text-align: center;">
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <strong id="block-new-customer-heading" role="heading" aria-level="2" style="font-size: 1.8rem;font-weight: 500;"><?= $block->escapeHtml(__('Are you new to Philippine Seashells Website?')) ?></strong>
        <div class="actions-toolbar">
            <div class="primary" style="float:none;">
                <a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create primary"><span><?= $block->escapeHtml(__('Create an Account')) ?></span></a>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
